spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://user-service-db.c8vicgiaqxzb.us-east-1.rds.amazonaws.com:3306/userservice
    username: admin
    password: adminroot
    driver-class-name: com.mysql.cj.jdbc.Driver