spring:
  application:
    name: Capstone-User-Service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
#  datasource:
#    url: jdbc:mysql://user-service-db.c8vicgiaqxzb.us-east-1.rds.amazonaws.com:3306/userservice
#    username: admin
#    password: adminroot
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/capstone_user
    username: root
    password: adminroot
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${SERVER_PORT}
logging:
  level:
    root: info
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#    uri: